# Generated by Django 3.1.2 on 2020-11-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Todo',
            new_name='todo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Date added',
        ),
        migrations.AddField(
            model_name='todo',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
